services:
  thisrepo-testing:
    build: .
    image: socib-shoreline-extraction
    
    working_dir: /srv/socib-shoreline-extraction 
    command: >
      sh -c "git config --global --add safe.directory /srv/socib-shoreline-extraction &&
             tail -f /dev/null"
    volumes:
      - type: bind
        source: ./
        target: /srv/socib-shoreline-extraction